; SGF node: sequence generation + replication onto two member streams
[interfaces]
uni = eth iface=uni
uni:streams = compound_in
nniA = eth iface=brA
nniB = eth iface=brB

[objects]
Repl = Replicate
Gen  = SeqGen InitSeqStart=0

[streams]
compound_in:packet  = eth, cvlan
compound_in:match   = cvlan vid=10
compound_in:actions = Gen, after cvlan add rtag, Repl memberA memberB

memberA = edit cvlan.vid=100, send nniA
memberB = edit cvlan.vid=200, send nniB